[A11Y] Fix some Website Accessibility Issues
BlackPythonDevs/blackpythondevs.github.io pull request #276
Opened 2024-03-14 14:12 UTC by oleksis

Fixes #275

2024-03-14 14:13 UTC, kjaymiller commented
Can you include the screenshots with your changes. I think they will better showcase the changes you've Made

2024-03-14 14:46 UTC, kjaymiller requested changes
Please add screenshot of affected changes to compare with the original

2024-03-14 14:55 UTC, oleksis commented
The changes:

![image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/abef1f78-f9dc-4c2d-a84c-c4dcdb119a79)

2024-03-14 21:07 UTC, kjaymiller requested changes

2024-03-14 21:07 UTC, kjaymiller commented on assets/css/bpd.css
Why are the changes in the newsletter section when the newsletter wasn't flagged?

2024-03-14 22:51 UTC, oleksis commented
New changes: 

![image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/14d9f8db-83bf-4733-b81d-947781d8510e)

2024-03-15 06:32 UTC, oleksis commented
[Add alt attribute specifies an alternate text for an image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/pull/276/commits/ac20d0e9a260e34c176d4d8c22fe77fa3acd714d)

![image](https://github.com/BlackPythonDevs/blackpythondevs.github.io/assets/44526468/62382011-d829-4b29-b66b-48d503da8bd2)

2024-03-15 09:12 UTC, oleksis commented
The other issues for **A11y** are related to 'pico' CSS vs **white** and **dark** mode for the theme.

2024-03-15 19:40 UTC, oleksis reviewed
look good to me

2024-03-15 19:40 UTC, oleksis commented on assets/css/bpd.css
whtat changes?

2024-03-15 19:40 UTC, oleksis commented on assets/css/bpd.css
when the color for `pico` fix it, we can merge this PR ?

2024-03-16 16:49 UTC, kjaymiller approved these changes

2024-03-16 16:50 UTC, merged