[POST] Abigail Mesrenyame Dogbe Honored with Outstanding PyLady Award…
BlackPythonDevs/blackpythondevs.github.io pull request #331
Opened 2024-05-24 19:14 UTC by anoexpected

… at PyCon 2024

2024-05-24 19:15 UTC, kjaymiller commented
Great work. Let me get you the quotes that you need

2024-05-24 19:25 UTC, anoexpected commented
> Great work. Let me get you the quotes that you need

It's ok

2024-06-03 12:19 UTC, kjaymiller commented on _posts/2024-05-25-abigail-mesrenyame-dogbe-wins-inaugural-outstanding-pylady-award.md
> +<img src="https://mesreandfriends.org/wp-content/uploads/2024/03/Dogbe_Abigail-DSC07499-1-1-1.jpg" style="margin-right: 20px; width: 100px; height: 100px; border-radius: 50%;" alt="Abigail Mesrenyame
I'm a little worried about the size of this image being a little small. Any chance that we can use either of these images.

 - www/_assets/images/blog/opa_winners_2024.png from the Pyladies Post - https://github.com/pyladies/pyladies/pull/664/files#diff-8e7d78d3423230e223108a6ba66bc3117118e69807be64c5e69c695530eb6af3

Image (Please credit in alt) - https://x.com/takanory/status/1792299062248591644/photo/1

2024-06-03 12:20 UTC, kjaymiller requested changes
I left a comment in about the image. I think this is good to go after that and we'll wait until Pyladies makes their announcement and then we'll publish alongside of it.

2024-06-03 13:35 UTC, anoexpected commented
> I left a comment in about the image. I think this is good to go after that and we'll wait until Pyladies makes their announcement and then we'll publish alongside of it.

It's ok I saw the comment so I will change the image with the one you suggested and make it big right?

2024-07-22 19:21 UTC, kjaymiller commented
@anoexpected - we're still waiting on pyladies to make their post public

2024-07-22 19:22 UTC, kjaymiller commented
And it's live!

And oddly dated back IN MAY. We can go ahead and merge

2024-07-22 19:22 UTC, merged