add CSS padding to speakers list
BlackPythonDevs/blackpythondevs.github.io pull request #400
Opened 2024-08-28 23:40 UTC by mbuguadouglas

resolve issue #369, allowing for padding in speakers ul in the conference page

2024-08-29 13:00 UTC, kjaymiller commented
Couple of thoughts on this on @mbuguadouglas, but first thank you for putting in the work for this. 

The original issue was to do this for all `li` objects on the site that are in `article` tags. This would create a consistency across the website. 

Your change only applies to the speaker list.

I did some digging. Here are some things that we will need to verify:

- What templates wrap content in the `<article></article>`. Should more or less do this. 
  **For You** Can you verify that the template that the `conferences page` along with the other pages like `about.html` and `open-source-program.html` also are wrapped in `<article>` tags?
  
  - Can you replace your class with a more broad `article  > li` tag that would apply this across the website?
  
#### Bonus points.:
 
 Changes should be tested. I would love a pytest that uses playwright to evaluate the CSS values. - Learn more at - https://playwright.dev/docs/evaluating
 
 If you aren't able to do this, or need help we can file an issue and I'll be happy to work with you on this (Perhaps you can ping me in the BPD discord)

2024-08-29 13:00 UTC, kjaymiller requested changes
See Comment

2024-08-30 03:17 UTC, mbuguadouglas commented
Thanks for the prompt feedback @kjaymiller . And I think i get what youre saying in the first part, so Ill work on that. For the second part(on testing), i do not know much about that :laughing: but id be happy to learn along the way. Using the resource assigned, ill be sure to contact you incase of any issues.

2024-08-30 11:04 UTC, kjaymiller commented
I definitely get it. Let's get the change added and we can get the test implementation as another issue.

2024-08-31 13:42 UTC, mbuguadouglas commented
Handled the CSS stying bit thus resolving issue #369 .However the resulting issue brought up in #400 about playwright testing proved abit difficult to implement in code and I might need some more time to figure it out.

2024-09-01 15:31 UTC, kjaymiller approved these changes

2024-09-01 15:31 UTC, kjaymiller commented on _includes/conferences.html
> +  </article>
try this 

```
<div>
{% for conference in site.data.conferences %}
  <article class="conference">
    <h2>
      <a href="{{ conference.url }}">{{ conference.name }}</a> ({{ conference.dates }}) {% if conference.location != "_No response_" %}- {{ conference.location }}{% endif %}
    </h2>
    <p>Type: {{ conference.type }}</p>
    {% if conference.summary != "_No response_" %}
      {{ conference.summary | markdownify }}
    {% endif %}
    {% if conference.speaking != "_No response_" %}
      <h3>Speaking:</h3>
          {{ conference.speaking | markdownify }}
    {% endif %}
  </article>
    {% endfor %}
{% else %}
<b>No conferences</b>
{% endif %}
</div>
```

2024-09-01 15:32 UTC, merged