Updated the club page
BlackPythonDevs/blackpythondevs.github.io pull request #475
Opened 2024-09-28 13:41 UTC by Selasi3

2024-09-29 20:12 UTC, kjaymiller requested changes
Please address the mentioned changes.

2024-09-29 20:12 UTC, kjaymiller commented on _articles/es/club.md
Delete this file

2024-09-29 20:12 UTC, kjaymiller commented on _includes/club.html
this file should exist at the root and not in includes.

You'll also need to also add the frontmatter at the top

2024-09-29 20:12 UTC, kjaymiller commented on _includes/footer.html
This is part of a different issue. Please remove this change from the PR

2024-09-29 20:12 UTC, kjaymiller commented on _layouts/index.html
> +  {%- include club.html -%}
```suggestion
```

2024-09-29 20:12 UTC, kjaymiller commented on assets/css/bpd.css
This is part of a different issue. Please remove from this PR

2024-09-30 12:21 UTC, Selasi3 commented
Changes worked on

2024-09-30 12:21 UTC, closed without merging