URL UPDATED
BlackPythonDevs/blackpythondevs.github.io pull request #480
Opened 2024-09-29 12:28 UTC by PartishtaP

THE CONTENTS i.e. THE NEW URL HAVE BEEN ADDED TO THE REQUIRED FILE

2024-09-29 19:10 UTC, kjaymiller requested changes
Thank you for this contribution. There was a little more that needs to be added to the issue but this looks good.

2024-09-29 19:10 UTC, kjaymiller commented on _data/partnerships.yml
>    description: "When you use the promo code: <strong>bpd-20pc-1c1da</strong> at checkout, you will receive 10% off your course purchase. TalkPython Training will also donate 20% of the purchase to Bl
```suggestion
  description: "When you use the <a href="https://training.talkpython.fm/black-python-devs">Black Python Devs landing page</a> or use the promo code: <strong>bpd-20pc-1c1da</strong> at checkout, you will receive 10% off your course purchase. TalkPython Training will also donate 20% of the purchase to Black Python Devs."
```

2024-09-29 19:10 UTC, kjaymiller commented on _data/partnerships.yml
> +  url: "https://training.talkpython.fm/black-python-devs" # NEW URL UPDATED in _data/partnerships.yaml to now share affiliate landing page which provides an easier workflow for those that want to sup
```suggestion
  url: "https://training.talkpython.fm/black-python-devs" 
```

2024-09-30 04:15 UTC, PartishtaP commented
If no changes are required can you please merge it and add my name as a contributor.

2024-09-30 12:04 UTC, kjaymiller commented
> If no changes are required can you please merge it and add my name as a contributor.

There are changes requested which you can see in the PR.

2024-09-30 20:14 UTC, kjaymiller approved these changes

2024-09-30 20:14 UTC, kjaymiller commented on _data/partnerships.yml
> +  description: "When you use the <a href="https://training.talkpython.fm/black-python-devs">Black Python Devs landing page</a> or use the promo code: <strong>bpd-20pc-1c1da</strong> at checkout, you
```suggestion
  description: 'When you use the <a href="https://training.talkpython.fm/black-python-devs">Black Python Devs landing page</a> or use the promo code: <strong>bpd-20pc-1c1da</strong> at checkout, you will receive 10% off your course purchase. TalkPython Training will also donate 20% of the purchase to Black Python Devs.'
```

2024-09-30 20:19 UTC, kjaymiller requested changes

2024-09-30 20:19 UTC, kjaymiller commented on _data/partnerships.yml
> +  description: 'When you use the <a href="https://training.talkpython.fm/black-python-devs">Black Python Devs landing page</a> or use the promo code: <strong>bpd-20pc-1c1da</strong> at checkout, you
```suggestion
  description: 'When you use the <a href="https://training.talkpython.fm/black-python-devs">Black Python Devs landing page</a> or use the promo code: <strong>bpd-20pc-1c1da</strong> at checkout, you will receive 10% off your course purchase. TalkPython Training will also donate 20% of the purchase to Black Python Devs.'

```

2024-09-30 21:05 UTC, merged