Create Recap of First Black Python Devs in Person Meetup #382
BlackPythonDevs/blackpythondevs.github.io pull request #528
Opened 2024-10-13 15:31 UTC by AfiMaameDufie

## Issue Link 🔗: https://github.com/BlackPythonDevs/blackpythondevs.github.io/issues/382

**Issue**: #[Issue_Number] 382

## Type of Change

- [ ] Bug fix 🐞
- [ ] New feature/page
- [x] Documentation update
- [ ] Other

## Description 📋

Added a blog for the BPD Ghana Connect Meetup Recap

## Checklist ✅

- [x] Followed the [Code of Conduct](https://github.com/BlackPythonDevs/blackpythondevs.github.io?tab=coc-ov-file) and [Contribution Guide](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/469afd71943738b7209bfe56d5a4e35394fbaafc/CONTRIBUTING.md)
- [x] Ran `pre-commit run --all`
- [x] All tests pass locally
- [ ] Added tests (if applicable)
- [x] Documentation updated (if applicable)

## Additional Notes & Screenshots

<img width="1728" alt="Screenshot 2024-10-13 at 3 29 48 PM" src="https://github.com/user-attachments/assets/b3fee504-1fa9-482c-b8e3-53e02428c453">

Add any additional notes or comments that might be helpful for the reviewers.

2024-10-13 23:23 UTC, TimOsahenru reviewed
LGTM! Just a little suggestion—can we include a featured image as well? It's fine if none is available, something like this ![image](https://github.com/user-attachments/assets/b5b0215d-01e0-4c30-842d-ec895705df86). Thanks

2024-10-14 14:55 UTC, kjaymiller commented
@AfiMaameDufie - LGTM I agree with @TimOsahenru. A featured image would be great to add.

2024-10-14 14:59 UTC, AfiMaameDufie commented
@TimOsahenru , @kjaymiller 

In my commits, I removed large images since the checks were failing. I found it hard to compress the pictures; I tried a couple of times for the feature image.

I will try again at the end of the day and revert.

2024-10-14 15:01 UTC, kjaymiller commented
> @TimOsahenru , @kjaymiller
> 
> In my commits, I removed large images since the checks were failing. I found it hard to compress the pictures; I tried a couple of times for the feature image.
> 
> I will try again at the end of the day and revert.

I understand this issue. 

One suggestion would be to convert the file to webp (I can help you with that) and compress it down to the maximum size it needs to be (likly 1920x1080 or smaller).

2024-10-14 15:14 UTC, AfiMaameDufie commented
> > @TimOsahenru , @kjaymiller
> > In my commits, I removed large images since the checks were failing. I found it hard to compress the pictures; I tried a couple of times for the feature image.
> > I will try again at the end of the day and revert.
> 
> I understand this issue.
> 
> One suggestion would be to convert the file to webp (I can help you with that) and compress it down to the maximum size it needs to be (likly 1920x1080 or smaller).

ohhh, webp, thanks! Will do that and push again.

2024-10-14 15:51 UTC, TimOsahenru commented
@AfiMaameDufie not sure if this helps, but you can also try using this online tool https://imageresizer.com/ to resize the image.

2024-10-14 19:28 UTC, AfiMaameDufie commented
Pushed again @TimOsahenru 
Should I take out the image in the blog and just leave the feature image?

2024-10-15 07:58 UTC, TimOsahenru commented
@AfiMaameDufie I think we have the provision to display the other images you've included, it's fine to leave them. Thanks

2024-10-15 08:18 UTC, AfiMaameDufie commented
> @AfiMaameDufie I think we have the provision to display the other images you've included, it's fine to leave them. Thanks
Great, thank you.

2024-10-15 11:35 UTC, kjaymiller requested changes
@AfiMaameDufie - great work on this.

My changes are minor nitpicks (naming and some formatting)

2024-10-15 11:35 UTC, kjaymiller commented on _posts/2024-10-13-black-python-devs-ghana-event.md
> +![Black Python Devs Ghana Connect Meetup](/assets/images/bpd3.webp)
```suggestion
![Black Python Devs Ghana Connect Meetup](/assets/images/bpd3.webp)

```

2024-10-15 11:35 UTC, kjaymiller commented on _posts/2024-10-13-black-python-devs-ghana-event.md
> +![Black Python Devs Ghana Connect Meetup](/assets/images/bpd3.webp)
Unless the linter complainsI would include a space to get things on separate lines.

2024-10-15 11:35 UTC, kjaymiller commented on assets/images/bpd1.webp
I would name this something a little more specific like bpd-ghana-first-meetup-1.webp

2024-10-15 11:35 UTC, kjaymiller commented on assets/images/bpd3.webp
I would name this something a little more specific like bpd-ghana-first-meetup-3.webp (what happened to two?)

2024-10-17 11:11 UTC, kjaymiller commented
@AfiMaameDufie were you able to rename the files to something that would be more easily identifiable.

2024-10-17 11:16 UTC, kjaymiller commented on _posts/2024-10-13-black-python-devs-ghana-event.md
> +![Black Python Devs Ghana Connect Meetup](/assets/images/bpd3.webp)
@AfiMaameDufie don't forget to rename the files in the post as well

2024-10-17 11:41 UTC, AfiMaameDufie commented
@kjaymiller 

Final review please

2024-10-17 12:11 UTC, kjaymiller approved these changes

2024-10-17 12:12 UTC, merged