Logo image added to all articles without an image
BlackPythonDevs/blackpythondevs.github.io pull request #537
Opened 2024-10-21 21:25 UTC by TimOsahenru

## Issue Link 🔗:

**Issue**: #533

## Type of Change

- [ ] Bug fix 🐞
- [x] New feature/page
- [ ] Documentation update
- [ ] Other

## Description 📋

- **What:** Provide an overview of the issue this PR addresses. Explain the context and background information.

- **Why:** Describe why the changes are being made. Highlight key updates, new features, or bug fixes.

- **How:** Explain how these changes will affect the project or end-users.

## Checklist ✅

- [x] Followed the [Code of Conduct](https://github.com/BlackPythonDevs/blackpythondevs.github.io?tab=coc-ov-file) and [Contribution Guide](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/469afd71943738b7209bfe56d5a4e35394fbaafc/CONTRIBUTING.md)
- [x] Ran `pre-commit run --all`
- [x] All tests pass locally
- [ ] Added tests (if applicable)
- [ ] Documentation updated (if applicable)

## Additional Notes & Screenshots

Add any additional notes or comments that might be helpful for the reviewers.

2024-10-21 23:26 UTC, kjaymiller commented
Please explain your changes using the PR description template.

2024-10-21 23:28 UTC, kjaymiller commented
@TimOsahenru instead of adding the image to each of the blog posts... Why not apply the image once in the template.

This way if there is ever a change in the logo design we only need to change it in one place.

2024-10-21 23:28 UTC, kjaymiller requested changes
Check comments please

2024-10-22 06:52 UTC, TimOsahenru commented
> @TimOsahenru instead of adding the image to each of the blog posts... Why not apply the image once in the template.
> 
> This way if there is ever a change in the logo design we only need to change it in one place.

Gotcha! Thanks

2024-10-22 11:16 UTC, TimOsahenru commented
@kjaymiller new changes have been committed. Please help review. Thanks

2024-10-22 12:25 UTC, kjaymiller requested changes

2024-10-22 12:25 UTC, kjaymiller commented on Gemfile.lock
> +    activesupport (7.1.4.1)
This seems like a regression. I would consider updating your gems.

2024-10-22 12:25 UTC, kjaymiller commented on Gemfile.lock
> +    ffi (1.17.0)
Not sure why all of these are removed. This could be an issue with our builds.

2024-10-22 12:25 UTC, kjaymiller commented on Gemfile.lock
> +    mutex_m (0.2.0)
seems like things were added.

2024-10-22 12:25 UTC, kjaymiller commented on Gemfile.lock
> +  x86-linux
duplicates that remove the gnu

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2023-10-20-djangoconus.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2023-11-11-what-is-the-us-conference-city-diversity-metric.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2023-11-13-black-python-devs-represent-in-dsf-elections.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2023-12-14-dawn-wages-sarah-abderemane-and-djangonaut-space-awarded-the-malcolm-tredinnick-memorial-prize.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2023-12-14-sarah-abderemane-selected-to-the-django-software-foundation-board.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2024-01-12-black-python-devs-is-sponsoring-pytexas.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2024-01-25-marlene-mhangami-recognized-as-python-fellow.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2024-03-13-pycon-us-announcement.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2024-07-03-black-python-devs-running-for-2024-PSF-Board.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2024-08-15-python-morsels-black-python-devs-high-five.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented on _posts/2024-08-16-talkpython-training-partnership.md
> +featured_image: /assets/images/bpd_stacked.png
Do we want to remove these since it hardcodes the default image?

2024-10-22 12:25 UTC, kjaymiller commented
Reminder please update the PR Description

2024-10-23 21:27 UTC, TimOsahenru commented
Hello @kjaymiller I'm facing some challenges updating my `activesupport` to match the upstream's version. I've also attempted to use the upstream's Ruby version (3.3.5p100) but haven't been able to resolve it yet. I'll continue troubleshooting, but if I can't resolve this by the end of the week, I'll unassign myself from the task and offer guidance to whoever takes over, as well as issue #365

2024-10-24 22:36 UTC, closed without merging