refactor leadership model with the new leadership model style
BlackPythonDevs/blackpythondevs.github.io pull request #614
Opened 2024-12-13 01:18 UTC by TimOsahenru

## Issue Link 🔗:

**Issue**: #596 

## Type of Change

- [ ] Bug fix 🐞
- [x] New feature/page
- [ ] Documentation update
- [ ] Other

## Description 📋
Overhaul the leadership section with the new regional leadership model

## Checklist ✅

- [x] Followed the [Code of Conduct](https://github.com/BlackPythonDevs/blackpythondevs.github.io?tab=coc-ov-file) and [Contribution Guide](https://github.com/BlackPythonDevs/blackpythondevs.github.io/blob/469afd71943738b7209bfe56d5a4e35394fbaafc/CONTRIBUTING.md)
- [x] Ran `pre-commit run --all`
- [x] All tests pass locally
- [ ] Added tests (if applicable)
- [ ] Documentation updated (if applicable)

## Additional Notes & Screenshots

Add any additional notes or comments that might be helpful for the reviewers.

2024-12-13 17:45 UTC, kjaymiller requested changes
Updates to the actual roles... Please see suggestions. 

I also have #616 that I'm going to push through that will allow you to use the updated  files

2024-12-13 17:45 UTC, kjaymiller commented on _data/regional_leadership.yml
> +  title: Executor(Ghana)
```suggestion
  title: Executor(Africa)
```

2024-12-13 17:45 UTC, kjaymiller commented on _data/regional_leadership.yml
> +  title: Executor(US/Canada)
```suggestion
  title: Executor(North America)
```

2024-12-13 17:45 UTC, kjaymiller commented on _data/regional_leadership.yml
> +  image: /assets/images/bpd_stacked.png
```suggestion
  image: /assets/images/laz.webp
```

2024-12-13 17:45 UTC, kjaymiller commented on _data/regional_leadership.yml
> +  image: https://github.com/AfiMaameDufie.png
```suggestion
  image: /assets/images/afi.webp
```

2024-12-14 12:52 UTC, TimOsahenru commented
@kjaymiller pushed the suggested changes. Kindly review. Thanks

2024-12-14 14:21 UTC, kjaymiller requested changes
Looks good but I just notice you completely removed the global leadership team. 

I and Doreen are still working as the global executor and treasurer.

2024-12-14 16:06 UTC, TimOsahenru commented
Oops! I've made another push addressing that issue. Please help review again. Thanks

2024-12-16 18:03 UTC, kjaymiller requested changes
Last minor change:

2024-12-16 18:03 UTC, kjaymiller commented on _data/global_leadership.yml
> +  alt: photo of Velda
```suggestion
```

Velda is actually stepping down and these roles are effectively taking the place of the Vice Executor Role.

2024-12-16 18:06 UTC, kjaymiller approved these changes

2024-12-16 18:18 UTC, merged